site_name: Decred德信社区-中文指引

nav:
- 'decred简介': 'index.md'
- 'decred杂志精选': 'dcrmagazine/DCR Proposals Space.md'
- '去中心化自托管交易所': 'dcrdex/dcrdex.md'
- '去中心化提案系统': 'Proposal/Proposal.md'



theme: #readthedocs
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
        
  language: zh
  logo: imge/color.svg
  features:
    - navigation.instant
    #- navigation.tabs
    - navigation.sections
    #- navigation.path
    - search.share
  plugins:
    - search:
       lang: 
         - en
         - zh
       jieba_dict: dict.txt
       boost: 2 

search:
  




